const adminRoute = require("express").Router();
const fs = require("fs");

const { UserModel } = require("../model/user_model");
const { QRModel } = require("../model/qr.model");

// -------------->>>>> All Users <<<<<---------------
adminRoute.get("/allUsers", async (req, res) => {
  try {
    let data = await UserModel.find();
    res.send({ msg: "All Data", data: data });
  } catch (error) {
    console.log(error);
    res.send({ msg: "Error in Fetching Details" });
  }
});

// ------------->>>>> Qr by Users <<<<<---------------
adminRoute.get("/allUsersQR/:id", async (req, res) => {
  const id = req.params.id;
  try {
    let data = await QRModel.find({userID:id});
    if(data.length==0){
      return res.send({ msg: "No QR Generated by User"});
    }
    res.send({ msg: "All QR Generated by User", data: data });
  } catch (error) {
    console.log(error);
    res.send({ msg: "Error in Fetching Details" });
  }
});

// ------->>>>> Delete a User from DB <<<<<-----------
adminRoute.delete("/deleteUser/:id", async (req, res) => {
  const id = req.params.id;
  try {
    await UserModel.findByIdAndDelete({ _id: id });
    res.send({ msg: `User has been Deleted` });
  } catch (err) {
    console.log(err);
    res.send({ msg: `Can't Deleted` });
  }
});

// ------->>>>> Get all Blocked Users <<<<------------
adminRoute.get("/blocked/Users", async (req, res) => {
  try {
    let data = await UserModel.find({status:false})
    console.log(data)
    res.send({msg:'Blocked User',data:data});
  } catch (err) {
    res.send({ msg:'No Blocked Users' });
  }
});

// ------------->>>>> Block User <<<<<---------------
adminRoute.post("/blockUser/:id", async (req, res) => {
  let id = req.params.id;
  try {
    await UserModel.findByIdAndUpdate(id, { status: false });
    res.send({ msg: "User is Blocked Now" });
  } catch (err) {
    res.send({ msg: "Error in Blocking" });
  }
});

// ------------>>>>> Unblock User <<<<<--------------
adminRoute.post("/unblockUser/:id", async (req, res) => {
  let id = req.params.id;
  try {
    await UserModel.findByIdAndUpdate(id, { status: true });
    res.send({ msg: "User is Unblocked Now" });
  } catch (err) {
    res.send({ msg: "Error in Blocking" });
  }
});

module.exports = {
  adminRoute,
};
